### ISSUE TITLE
brackets highlighting 

### ISSUE THREAD

**Issue by monouser7dig** [crystal-lang-tools/sublime-crystal#27] opened 2017-10-05 18:39 UTC
```
  def initialize(states : State(S, A))
    @states << states
  end
```
have an issue at State(>>>(<<<S,A))

using sublime 3 and Monokai, Mariana or other themes (just plain, no special config afaik)

thanks for auto format in sublime, works great!

**Comment by faustinoaq** [comment] 2017-10-06 07:31
I think this is a duplicate of #23 already fixed on #24 
The problem would be that published package on Sublime Package Manager is not updated.

Maybe @bcardiff or someone with access to sublime published package will update this.

**Comment by monouser7dig** [comment] 2017-10-06 07:33
just updated to yet a more recent sublime version that came out today and run upgrade package but issue persists so dunno if it is fixed or not published or ...

**Comment by faustinoaq** [comment] 2017-10-06 07:40
> it is fixed or not published

I think so

**Comment by fgimian** [comment] 2018-06-26 12:02
This looks good to me now:

![screen shot 2018-06-26 at 10 01 16 pm](https://user-images.githubusercontent.com/1811813/41910268-80fcaae2-798c-11e8-88a0-ebeeece55c35.png)

@monouser7dig Do you think it's OK to close this issue now?  If so, please go ahead 😄 

Cheers
Fotis

**Closed** 2018-06-26 12:14 UTC
Labels: enhancement
